import React from "react";
import BlogDetailImageCard from "../../components/Blog/BlogDetailImageCard";
import { Container, Breadcrumb } from "react-bootstrap";
import { useNavigate } from "react-router-dom";
import classes from "./BlogDetails.module.css";

const BlogsDetails = () => {
  const navigate = useNavigate();
  return (
    <Container style={{ marginTop: "30px" }}>
      <Breadcrumb>
        <Breadcrumb.Item onClick={() => navigate("/")}>Home</Breadcrumb.Item>
        <Breadcrumb.Item onClick={() => navigate("/blog")}>
          {`All Blogs`}
        </Breadcrumb.Item>
        <Breadcrumb.Item active>{`food`}</Breadcrumb.Item>
      </Breadcrumb>
      <BlogDetailImageCard
        image={
          "https://storage.googleapis.com/aawaz-stateless/2019/12/health-benefits-of-surya-namaskar-640x480.jpg"
        }
      />

      <Container>
        <div className={classes.BlogContant}>
          <p>
            Surya Namaskar” or Sun-salutation is an ancient method of expressing
            gratitude towards the sun, which is the source of all forms of life
            and energy on earth. It is a sequence of twelve yogic postures or
            asanas performed as a continuous exercise. There was a tradition of
            offering “arghya” to the sun in the ancient times, Surya Namaskar is
            a more advanced way of doing the same while gaining mental,
            physical, spiritual and physiological benefits.
          </p>
          <h4> 7 Health Benefits of Surya Namaskar</h4>
          <div className={classes.ImageWrap}>
            <img src="https://storage.googleapis.com/aawaz-stateless/2019/12/1-half-sequence-of-the-practice-500x360.jpg" />
          </div>
          <li>
            Surya Namaskar is a complete exercise that exerts its effects on
            every part of the body. Practice of Suryanamaskar makes the body
            flexible. It especially improves the flexibility of the spine and
            limbs. Flexibility of the spine means bye-bye back and neck
            problems!
          </li>
          <li>
            The practice of inhalation and exhalation while performing Surya
            Namaskar enhances the blood circulation in the body. This regulates
            the blood pressure and benefits in case of low and high blood
            pressure. The act of deep breathing flushes out toxins from the body
            increasing alertness, productivity and making one feel more alive
            than before.
          </li>
          <li>
            Surya Namaskar stimulates the brain cells in the body hence
            preventing memory loss. The practice also helps in building focus
            and concentration by improving the functioning of brain.
          </li>
          <div className={classes.ImageWrap}>
            <img src="https://storage.googleapis.com/aawaz-stateless/2019/12/2-women-highly-benefit-through-regular-practice-of-suryanamaskar-500x360.jpg" />
          </div>
          <li>
            Since young women are in sync with nature’s lunar cycles, they
            highly benefit from the regular practice of Suryanamaskar as their
            menstrual cycle becomes regular and pain-free.
          </li>
          <li>
            Adding the mantras during the practice removes monotony, brings
            harmony and produces soothing vibrations that drive away fatigue.
            The act of surrendering yourself to the sun removes the self-binding
            ego in the practitioner.
          </li>
          <li>
            The sun being the ultimate source of energy provides abundant energy
            to the practitioner thereby leaving their skin glowing and radiant.
            It also enhances vigour and vitality and boosts the strength of the
            body organs.
          </li>
          <li>
            Surya Namaskar practice is the ideal exercise to cure the insomnia
            problem. It basically calms the mind. Due to the unique breathing
            pattern, the mind feels relaxed completely thus improving the sleep
            patterns of the person practicing it.
          </li>
          <div className={classes.ImageWrap}>
            <img src="https://storage.googleapis.com/aawaz-stateless/2019/12/3-sunrise-the-best-time-to-practice-suryanamaskar-500x360.jpg" />
          </div>
          <p>
            The best time to practice Surya Namaskar is at sunrise because at
            that time, the sun’s radiations are nourishing and soothing in
            nature. It is best practiced after a cold water bath. The
            temperature of the water should be 3-4 degrees lesser than the room
            temperature. This aids in the contraction of the intercellular
            spaces, thus filling the spaces with energy that is generated by the
            practice. So, Surya Namaskar is a complete workout for the mind,
            body and the soul. It transforms the individual by working on all
            energy centers. However, it is important to note than any form of
            exercise should be consciously learnt under an instructor and one
            must avoid self-learning to prevent injuries or ill-effects of wrong
            practice.
          </p>
        </div>
      </Container>
    </Container>
  );
};

export default BlogsDetails;
